// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDldQ8a_Om9m2eNUs5xeLE3deQw1g48do',
    appId: '1:1026260560363:web:2ece09cce3b14396e1d1ae',
    messagingSenderId: '1026260560363',
    projectId: 'banger-1eb74',
    authDomain: 'banger-1eb74.firebaseapp.com',
    storageBucket: 'banger-1eb74.appspot.com',
    measurementId: 'G-Y73RW39ZD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdf5B9Yw7D_a0HBL2QnZ8u81492LdDWak',
    appId: '1:1026260560363:android:399cc7161b06e340e1d1ae',
    messagingSenderId: '1026260560363',
    projectId: 'banger-1eb74',
    storageBucket: 'banger-1eb74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe-DfjMNvlsRaN1M4P_YwxrAIkI5ocDB8',
    appId: '1:1026260560363:ios:34970c8578800a25e1d1ae',
    messagingSenderId: '1026260560363',
    projectId: 'banger-1eb74',
    storageBucket: 'banger-1eb74.appspot.com',
    iosClientId: '1026260560363-3lcqlo4bhlhf0eq0t5e0fdiv176namqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.bangerzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe-DfjMNvlsRaN1M4P_YwxrAIkI5ocDB8',
    appId: '1:1026260560363:ios:eb0415d19824735ae1d1ae',
    messagingSenderId: '1026260560363',
    projectId: 'banger-1eb74',
    storageBucket: 'banger-1eb74.appspot.com',
    iosClientId: '1026260560363-hsm3m4o0se96ui1j422f4uiuopnnn94s.apps.googleusercontent.com',
    iosBundleId: 'com.example.bangerzz.RunnerTests',
  );
}
